-- 用户表
CREATE TABLE SYS_USER(
	ID INT PRIMARY KEY AUTO_INCREMENT COMMENT '用户ID',
	USER_NAME VARCHAR(30) DEFAULT NULL COMMENT '用户名称',
	USER_PWD VARCHAR(255) NOT NULL COMMENT '用户密码',
	MOBILE_NO VARCHAR(20) DEFAULT NULL COMMENT '手机号码',
	STATUS CHAR(1) NOT NULL COMMENT '用户状态:1 可用,0 冻结',
	DEPT_ID INT NOT NULL COMMENT '部门ID',
	REMARK VARCHAR(255) DEFAULT NULL COMMENT '描述'
)