-- 用户表
CREATE TABLE sys_user (
  ID int(11) PRIMARY KEY AUTO_INCREMENT COMMENT '用户ID',
  LOGIN_NAME VARCHAR(30) NOT NULL COMMENT '登录名称',
  USER_NAME varchar(30) NOT NULL COMMENT '用户名称',
  USER_PWD varchar(255) NOT NULL COMMENT '用户密码',
  MOBILE_NO varchar(20) DEFAULT NULL COMMENT '手机号码',
  STATUS int(1) NOT NULL DEFAULT 1 COMMENT '用户状态:1 可用,2 冻结',
  REMARK varchar(255) DEFAULT NULL COMMENT '描述',
	CREATE_NAME VARCHAR(255) DEFAULT NULL COMMENT '创建人',
	UPDATE_NAME VARCHAR(255) DEFAULT NULL COMMENT '修改人',
	CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	UPDATE_TIME TIMESTAMP NULL COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户表';

-- 角色表
CREATE TABLE SYS_ROLE(
	ID INT(11) PRIMARY KEY AUTO_INCREMENT COMMENT '角色主键',
	ROLE_NAME VARCHAR(255) NOT NULL COMMENT '角色名称',
	STATUS int(1) NOT NULL DEFAULT 1 COMMENT '状态:1 可用,2 冻结',
	OPERATE_NAME VARCHAR(255) DEFAULT NULL COMMENT '操作人',
	UPDATE_NAME VARCHAR(255) DEFAULT NULL COMMENT '修改人',
	
	CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	UPDATE_TIME TIMESTAMP NULL COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='角色表';

-- 权限表
CREATE TABLE SYS_PERMISSION(
	ID INT(11) PRIMARY KEY AUTO_INCREMENT COMMENT '权限主键',
	PERMISSION_NAME VARCHAR(255) NOT NULL COMMENT '权限名称',
	PERMISSION_DESC VARCHAR(255) DEFAULT NULL COMMENT '权限描述',
	PERMISSION_URL VARCHAR(255) NOT NULL COMMENT '权限URL',
	PERMISSION_TYPE VARCHAR(255) NOT NULL COMMENT '权限类型: 0 目录   1 菜单   2 按钮',
 	PID INT(11) NOT NULL DEFAULT 0 COMMENT '父节点id',
 	STATUS int(1) NOT NULL DEFAULT 1 COMMENT '状态:1 可用,2 冻结',
	OPERATE_NAME VARCHAR(255) DEFAULT NULL COMMENT '创建人',
	UPDATE_NAME VARCHAR(255) DEFAULT NULL COMMENT '修改人',
	CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	UPDATE_TIME TIMESTAMP NULL COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='权限表';

-- 角色用户关联表
CREATE TABLE SYS_ROLE_USER(
	ID INT(11) PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
	SYS_USER_ID INT(11) NOT NULL COMMENT '用户ID',
	SYS_ROLE_ID INT(11) NOT NULL COMMENT '角色ID',
	OPERATE_NAME VARCHAR(255) DEFAULT NULL COMMENT '创建人',
	UPDATE_NAME VARCHAR(255) DEFAULT NULL COMMENT '修改人',
	CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	UPDATE_TIME TIMESTAMP NULL COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='角色用户关联表';


-- 角色权限关联表
CREATE TABLE SYS_ROLE_PERMISSION(
	ID INT(11) PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
	SYS_PERMISSION_ID INT(11) NOT NULL COMMENT '权限ID',
	SYS_ROLE_ID INT(11) NOT NULL COMMENT '角色ID',
	OPERATE_NAME VARCHAR(255) DEFAULT NULL COMMENT '创建人',
	UPDATE_NAME VARCHAR(255) DEFAULT NULL COMMENT '修改人',
	CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	UPDATE_TIME TIMESTAMP NULL COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='角色权限关联表';

--日志操作表
DROP TABLE IF EXISTS SYS_OPERATE_LOG;
CREATE TABLE SYS_OPERATE_LOG(
	ID INT(11) PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
	OPERATE_METHOD VARCHAR(255) NOT NULL COMMENT '操作方法',
	IS_SUCCESS INT(1) NOT NULL COMMENT '是否操作成功 1 成功 2 异常',
	ERROR_CODE VARCHAR(255) DEFAULT NULL COMMENT '异常code',
	ERROR_MSG VARCHAR(255) DEFAULT NULL COMMENT '异常信息',
	OPERATE_NAME VARCHAR(255) DEFAULT NULL COMMENT '创建人',
	UPDATE_NAME VARCHAR(255) DEFAULT NULL COMMENT '修改人',
	CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	UPDATE_TIME TIMESTAMP NULL COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='日志操作表';